Fix command line to use kivy instead of python
Using official Kivy 1.8.0 on OSX,
attempting to run ‘python main.py’ results in the following error:
 ImportError: cannot import name actionbar

Running ‘kivy main.py’ works just fine.